version: "3"

services:
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    db:
        image: bitnami/postgresql:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: api_ecommerce
        volumes:
          - ./app/migrations:/docker-entrypoint-initdb.d
